### ISSUE TITLE
Responsive: UI is broken when width is 990 - 1200

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#12]
![image](https://user-images.githubusercontent.com/710513/28109196-dcf81c22-66f6-11e7-8d38-caee0a2a3a25.png)

**Comment by andrewQwer** [comment]
![image](https://user-images.githubusercontent.com/710513/28109277-34166f40-66f7-11e7-9cd0-f007164824f1.png)

**Comment by pkarpovich** [comment]
fixed in BEM task
