### ISSUE TITLE
ArrayTools - непонятный вызов

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#20]
`var sortedArray = JSON.parse(JSON.stringify(array));` не очень понял для чего ты это делаешь.

Если для создания копии, то есть более красивые пути: https://stackoverflow.com/questions/3978492/javascript-fastest-way-to-duplicate-an-array-slice-vs-for-loop

**Comment by pkarpovich** [comment]
would be fixed in the following commits
