### ISSUE TITLE
sql task - группировка

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#25]
-- a. Найти среднюю начисленную заработную плату за 2015 год в разрезе работников;
  SELECT avg(Salary) as avgSalary
  FROM Salary
  WHERE Year = 2015

Это просто средняя заработная плата за 2015 год, нужна средняя по каждому работнику

**Comment by pkarpovich** [comment]
would be fixed in the following commits
