### ISSUE TITLE
sql task - использование *

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#26]
-- a. Найти имена тех работников, начисленная заработная плата которых за январь 2015 превысила 1000;
  SELECT *
  FROM Employee
    INNER JOIN Salary ON Employee.Id = Salary.EmployeeId
  WHERE Year = 2015 AND Month = 1 AND Salary > 1000

Лучше явно перечислять поля, необходимые для выборки. Т.к. * в итоге может выбрать огромное количество ненужных полей, занимающих память в выборке

**Comment by pkarpovich** [comment]
would be fixed in the following commits
