### ISSUE TITLE
Task 4 - magic strings

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#29]
Класс `Ticket` в методе `switchStatus` использует строки типа "Open", "Closed", "InProgress" - такие вещи выносятся в константы для переиспользования, т.к. велика вероятность опечатки например вместо "InProgress" написать "In Progress". Использование констант вместо строк, чисел, других примитивных типов данных повышает понимание кода и уменьшает количество ошибок в будущем.

**Comment by pkarpovich** [comment]
В будущих проектах буду вносить строки в константы.
