### ISSUE TITLE
Используешь C# нотацию для интерфейсов

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#38]
В JS не приняты именования классов типа IType, IObserver и т.д., это больше характерно для TypeScript. И если взять тот же IType, то классы Admin, PremiumUser, SimpleUser его почему-то не наследуют, что еще больше сбивает с толку

**Comment by pkarpovich** [comment]
Иерархия типов была перенесена на сторону сервера.
