### ISSUE TITLE
Action types hint

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#41]
Чтобы не дублировать значение экшн тайпов можно воспользоваться таким способом:
```
import keyMirror from 'keymirror';

export const actionTypes = keyMirror({
    NOTIFICATION_SETTINGS_EDIT: null,
    NOTIFICATION_SETTINGS_CANCEL: null,
    NOTIFICATION_SETTINGS_SAVE: null
});
```
Библиотека keymirror как говорит название дублирует название ключей в значения.

**Comment by pkarpovich** [comment]
Начал использовать библиотеку keyMirror.
