### ISSUE TITLE
DOM manipulation and react

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#45]
```
let checkBoxes = document.querySelectorAll("input[type=checkbox]");
		for (let item of checkBoxes) {
			if ($(item).get(0).checked) {
				$(item).prop("checked", false);
			}
		}
```
такого в коде у тебя не должно быть, т.к. React хранит виртуальный дом в своей памяти и только он должен его обновлять. Если ты обновляешь DOM вне React могут произойти различного рода коллизии. Вся разметка управляется либо через props либо через state и никак иначе

**Comment by pkarpovich** [comment]
Функции jQuery были удалены. Изменения в следующих коммитах.
