### ISSUE TITLE
setState and immutability

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#46]
```
let original = this.toDeleteArray;
		original.includes(uuidValue)
			? original.splice(original.indexOf(uuidValue), 1)
			: original.push(uuidValue);
		this.toDeleteArray = original;
```
ссылка на массив original не меняется, если использован метод push. По хорошему со стейтом надо обращтся как с Immutable сущностью.
Т.е. правильнее было бы что-то типа: `this.toDeleteArray = [...original];`

**Comment by pkarpovich** [comment]
Будет исправлено в следующих коммитах.
