### ISSUE TITLE
dynamic class names

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#48]
```
className={`alert alert-success ${!!this.props.text
					? "notification__block--show"
					: "notification__block--hide"}`}
```
чтобы такого избежать можно использовать библиотеку `classnames`, который позволяет динамически генерировать набор классов по набору булевских свойств.

**Comment by pkarpovich** [comment]
В проект была добавлена библиотека **classnames**. Изменения будут в следующих коммитах.
