### ISSUE TITLE
Немного странная проверка на роуты

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#49]
У роутера есть метод onEnter, который как раз таки  и нужен для проверки прав и всего остального до ренедра компонента. У тебя же наоборот, извне проверяешь права и уже на основе этого генеришь набор роутов. Код становится менее понятным, т.к. по сути получаются динамические роуты.

**Comment by pkarpovich** [comment]
В последней версии react-router данный функционал [был удален](https://github.com/ReactTraining/react-router/issues/4699).
