### ISSUE TITLE
Link text should go inside a tag, not by :after pseudo elemnt

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-pavel.karpovich#6]
Usually, link text is placed inside a tag like this: `<a> text </a>` This gives you better control over text when it is dynamic and depends on page state or value comes from the backend.
Placing it to `content: <...>` CSS property gives you less control over it.

**Comment by pkarpovich** [comment]
link texts were moved from CSS to tag in BEM task
